version: '3'
services:
  db:
    image: mongo:4.4
    ports:
    - 27017:27017
  jaeger:
    image: jaegertracing/all-in-one:1.22
    command:
    - --processor.jaeger-binary.server-host-port
    - :6832
    ports:
    - 16686:16686
    - 6832:6832/udp